// <auto-generated />
namespace ClubDomainClasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentsCoursesseeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentsCoursesseeding));
        
        string IMigrationMetadata.Id
        {
            get { return "202201061449307_Students & Courses seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
