// <auto-generated />
namespace Solution_Banking_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initalseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initalseed));
        
        string IMigrationMetadata.Id
        {
            get { return "202201061724382_Inital seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
